# Generated by Django 6.0.3 on 2026-06-02 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_report_status'),
        ('main_app', '0002_report_reporter_report_updated_at_and_more'),
    ]

    operations = [
    ]
